# Generated by Django 5.0.1 on 2024-01-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='presentations.tag'),
        ),
    ]
