# Generated by Django 5.0.1 on 2024-02-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0004_alter_presentation_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presentation',
            old_name='tag',
            new_name='tags',
        ),
        migrations.AlterField(
            model_name='presentation',
            name='background',
            field=models.ImageField(upload_to='images/presentation/'),
        ),
    ]
