# Generated by Django 5.0.1 on 2024-02-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0005_rename_tag_presentation_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='presentations.tag'),
        ),
    ]
