# Generated by Django 5.0.1 on 2024-02-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0006_alter_presentation_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='slug',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
    ]
