# Generated by Django 5.0.1 on 2024-02-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0007_presentation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='full_name_presenter',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
