# Generated by Django 5.0.1 on 2024-02-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='tags',
            field=models.ManyToManyField(blank=True, to='presentations.tag'),
        ),
    ]
