# Generated by Django 5.0.1 on 2024-02-19 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0005_alter_presentation_background'),
        ('slide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='presentation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentation_slide', to='presentation.presentation'),
        ),
    ]
