# Generated by Django 5.0.1 on 2024-02-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='full_name_presenter',
        ),
        migrations.AddField(
            model_name='presentation',
            name='presenter',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='slug',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='tags',
            field=models.ManyToManyField(null=True, to='presentation.tag'),
        ),
    ]
