# Generated by Django 5.0.1 on 2024-02-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0003_remove_presentation_full_name_presenter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='tags',
            field=models.ManyToManyField(blank=True, to='presentation.tag'),
        ),
    ]
