# Generated by Django 5.0.1 on 2024-02-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0004_alter_presentation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='background',
            field=models.ImageField(blank=True, upload_to='images/presentation/'),
        ),
    ]
