# Generated by Django 5.0.1 on 2024-02-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0005_alter_presentation_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='images/presentation/'),
        ),
    ]
